/**
 * Vite plugin that generates sitemap.xml for the landing page at build time.
 * Docs and blog sitemaps are generated by Docusaurus separately.
 */

import { type Plugin } from "vite";
import fs from "fs";
import path from "path";

const SITE_URL = "https://pilot-shell.com";

export default function sitemapPlugin(): Plugin {
  let outDir: string;

  return {
    name: "generate-sitemap",
    apply: "build",

    configResolved(config) {
      outDir = config.build.outDir;
    },

    closeBundle() {
      const today = new Date().toISOString().split("T")[0];

      const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${SITE_URL}/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
`;

      const dest = path.resolve(outDir, "sitemap.xml");
      fs.writeFileSync(dest, xml);
      console.log(`\x1b[32m✓\x1b[0m sitemap.xml generated (landing page)`);
    },
  };
}
